// import Head from "next/head";
import MainSecion01 from "../components/home/MainSecion01";
import DefaultLayout from "../components/layout";

export default function Home() {
  return (
    <DefaultLayout>
      {/* <Head>
        <title>Hello!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <MainSecion01 />
          </div>
        </section>
      </main>
    </DefaultLayout>
  );
}
