// import Head from "next/head";
import DefaultLayout from "../components/layout";

export default function Home() {
  return (
    <DefaultLayout>
      {/* <Head>
        <title>Hello!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        <h2>Hello World!</h2>
      </main>
    </DefaultLayout>
  );
}
